stages:
  - test
  - build
  - deploy staging

variables:
  CI_REGISTRY_IMAGE_DETAILS: registry.gitlab.com/shaurya_mehta/employee-portal
  STAGING_APP: emp-portal-stagee
  HEROKU_STAGING: "registry.heroku.com/$STAGING_APP/web"
  DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_AUTH" } }}'
  # $CI_REGISTRY_IMAGE = registry.gitlab.com/shaurya_mehta/employee-portal

lint_test:
  stage: test
  image: python:3.8.0-slim
  
  before_script:
    - pip install flake8-html
  script:
    - flake8 --format=html --htmldir=flake-report
  artifacts:
    when: always
    paths:
      - flake-report/
  
pytest:
  stage: test
  image: python:3.8.0-slim

  before_script:
    - pip install pytest-html
    - pip install -r requirements.txt
  script:
    - pytest --html=pytest_reports/pytest_reports.html
  artifacts:
    when: always
    paths:
      - flake-report/

build:
  image: docker:latest
  services: 
    - docker:dind
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - docker build -t $CI_REGISTRY_IMAGE_DETAILS/employee-image:$CI_COMMIT_REF_SLUG .
    - docker images
    - docker push $CI_REGISTRY_IMAGE_DETAILS/employee-image:$CI_COMMIT_REF_SLUG

deploy_stage:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy staging
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE_DETAILS/employee-image:$CI_COMMIT_REF_SLUG
    - docker tag  $CI_REGISTRY_IMAGE_DETAILS/employee-image:$CI_COMMIT_REF_SLUG $HEROKU_STAGING
    - docker login -u _ -p $HEROKU_STAGING_API_KEY registry.heroku.com
    - docker push $HEROKU_STAGING